# Generated by Django 4.1.7 on 2023-03-28 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deliverer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deliverer_name", models.CharField(max_length=510)),
                (
                    "deliverer_image",
                    models.FileField(
                        blank=True, null=True, upload_to="deliverer_images"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=120)),
                ("note", models.CharField(max_length=400)),
                ("status", models.CharField(max_length=400)),
                ("date_created", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_fee", models.IntegerField(blank=True, null=True)),
                ("clearance_fee", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reciever",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=120)),
                ("photo_image", models.ImageField(upload_to="reciever_images")),
            ],
        ),
        migrations.CreateModel(
            name="SendEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("reciever_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.CharField(blank=True, max_length=120, null=True)),
                ("quantity", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "mode_of_shipment",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "shipment_pick_up_date",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "shipment_type",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("comment", models.CharField(blank=True, max_length=120, null=True)),
                ("uuid", models.TextField(unique=True)),
                (
                    "registered_at_location",
                    models.CharField(default="Texas", max_length=30),
                ),
                (
                    "destination",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "deliverer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.deliverer"
                    ),
                ),
                ("location", models.ManyToManyField(to="base.location")),
                (
                    "payments",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.payment",
                    ),
                ),
                (
                    "reciever",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.reciever"
                    ),
                ),
            ],
        ),
    ]
